# Generated by Django 4.0.4 on 2022-06-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/1/1e/Default-avatar.jpg', max_length=200),
        ),
    ]
